// Centralized Supabase client - env first, fallback to autogenerated info
import { createClient } from '@supabase/supabase-js';

const ENV_URL = import.meta.env?.VITE_SUPABASE_URL as string | undefined;
const ENV_ANON = import.meta.env?.VITE_SUPABASE_ANON_KEY as string | undefined;

// Fallback values from autogenerated file (kept for compat)
// These are public anon values - safe to expose, but should be overridden by env in prod
const FALLBACK_PROJECT_ID = 'vgofxfjbcaplgrhodxmn';
const FALLBACK_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnb2Z4ZmpiY2FwbGdyaG9keG1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1MjE3MjEsImV4cCI6MjA4OTA5NzcyMX0.iRI_xV4Eqfc5i5D8EYDNMZWcXRkLYaItG13H0QgAMiw';

export function getSupabaseConfig() {
  // Determine URL and keys
  let supabaseUrl = ENV_URL;
  let supabaseAnonKey = ENV_ANON;
  let projectId = FALLBACK_PROJECT_ID;
  let publicAnonKey = FALLBACK_ANON_KEY;

  // If ENV_URL provided, try to extract projectId from subdomain
  if (supabaseUrl) {
    try {
      const url = new URL(supabaseUrl);
      const hostPart = url.hostname.split('.')[0];
      if (hostPart && hostPart !== 'localhost' && hostPart !== '127') {
        projectId = hostPart;
      }
    } catch {
      // ignore, keep fallback
    }
  } else {
    supabaseUrl = `https://${projectId}.supabase.co`;
  }

  if (!supabaseAnonKey) {
    supabaseAnonKey = publicAnonKey;
  } else {
    publicAnonKey = supabaseAnonKey;
  }

  return {
    supabaseUrl,
    supabaseAnonKey,
    projectId,
    publicAnonKey,
  };
}

const cfg = getSupabaseConfig();

export const projectId = cfg.projectId;
export const publicAnonKey = cfg.publicAnonKey;
export const SUPABASE_URL = cfg.supabaseUrl;
export const SUPABASE_ANON_KEY = cfg.supabaseAnonKey;
export const SUPABASE_FUNCTIONS_URL = `${cfg.supabaseUrl}/functions/v1`;

export function getEdgeFunctionUrl(path: string): string {
  const clean = path.replace(/^\/+/, '');
  return `${SUPABASE_FUNCTIONS_URL}/${clean}`;
}

export const supabase = createClient(cfg.supabaseUrl, cfg.supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});
