// Centralized Supabase client for the embedded ScoreHub app.
// ScoreHub runs against its own Supabase project (vgofxfjbcaplgrhodxmn) and
// must NOT inherit the host social app's generic VITE_SUPABASE_URL.
// Override with VITE_SCOREHUB_SUPABASE_URL / VITE_SCOREHUB_SUPABASE_ANON_KEY.
import { createClient } from '@supabase/supabase-js';
import { projectId as INFO_PROJECT_ID, publicAnonKey as INFO_ANON_KEY } from '../livescore-supabase/info';

const ENV_URL = process.env.NEXT_PUBLIC_SCOREHUB_SUPABASE_URL ?? process.env.VITE_SCOREHUB_SUPABASE_URL as string | undefined;
const ENV_ANON = process.env.NEXT_PUBLIC_SCOREHUB_SUPABASE_ANON_KEY ?? process.env.VITE_SCOREHUB_SUPABASE_ANON_KEY as string | undefined;

// Fallback values from autogenerated file (kept for compat)
// These are public anon values - safe to expose, but should be overridden by env in prod
const FALLBACK_PROJECT_ID = INFO_PROJECT_ID;
const FALLBACK_ANON_KEY = INFO_ANON_KEY;

export function getSupabaseConfig() {
  // Determine URL and keys
  let supabaseUrl = ENV_URL;
  let supabaseAnonKey = ENV_ANON;
  let projectId = FALLBACK_PROJECT_ID;
  let publicAnonKey = FALLBACK_ANON_KEY;

  // If ENV_URL provided, try to extract projectId from subdomain
  if (supabaseUrl) {
    try {
      const url = new URL(supabaseUrl);
      const hostPart = url.hostname.split('.')[0];
      if (hostPart && hostPart !== 'localhost' && hostPart !== '127') {
        projectId = hostPart;
      }
    } catch {
      // ignore, keep fallback
    }
  } else {
    supabaseUrl = `https://${projectId}.supabase.co`;
  }

  if (!supabaseAnonKey) {
    supabaseAnonKey = publicAnonKey;
  } else {
    publicAnonKey = supabaseAnonKey;
  }

  return {
    supabaseUrl,
    supabaseAnonKey,
    projectId,
    publicAnonKey,
  };
}

const cfg = getSupabaseConfig();

export const projectId = cfg.projectId;
export const publicAnonKey = cfg.publicAnonKey;
export const SUPABASE_URL = cfg.supabaseUrl;
export const SUPABASE_ANON_KEY = cfg.supabaseAnonKey;
export const SUPABASE_FUNCTIONS_URL = `${cfg.supabaseUrl}/functions/v1`;

export function getEdgeFunctionUrl(path: string): string {
  const clean = path.replace(/^\/+/, '');
  return `${SUPABASE_FUNCTIONS_URL}/${clean}`;
}

export const supabase = createClient(cfg.supabaseUrl, cfg.supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});
