alter table public.profiles
  add column if not exists county text,
  add column if not exists constituency text;

alter table public.posts
  add column if not exists visibility text not null default 'public' check (visibility in ('public', 'county', 'constituency')),
  add column if not exists county text,
  add column if not exists constituency text;

update public.profiles
set
  county = split_part(location, ', ', 2),
  constituency = split_part(location, ', ', 1)
where location like '%, %'
  and (county is null or constituency is null);

update public.posts
set visibility = 'public'
where visibility is null;

create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  county text not null,
  constituency text not null,
  unique (county, constituency)
);

insert into public.locations (county, constituency) values
  ('Baringo', 'Baringo Central'), ('Baringo', 'Baringo North'), ('Baringo', 'Baringo South'), ('Baringo', 'Eldama Ravine'), ('Baringo', 'Mogotio'), ('Baringo', 'Tiaty'),
  ('Bomet', 'Bomet Central'), ('Bomet', 'Bomet East'), ('Bomet', 'Chepalungu'), ('Bomet', 'Konoin'), ('Bomet', 'Sotik'),
  ('Bungoma', 'Bumula'), ('Bungoma', 'Kabuchai'), ('Bungoma', 'Kanduyi'), ('Bungoma', 'Kimilili'), ('Bungoma', 'Mt. Elgon'), ('Bungoma', 'Sirisia'), ('Bungoma', 'Tongaren'), ('Bungoma', 'Webuye East'), ('Bungoma', 'Webuye West'),
  ('Busia', 'Budalangi'), ('Busia', 'Butula'), ('Busia', 'Funyula'), ('Busia', 'Matayos'), ('Busia', 'Nambale'), ('Busia', 'Teso North'), ('Busia', 'Teso South'),
  ('Elgeyo-Marakwet', 'Keiyo North'), ('Elgeyo-Marakwet', 'Keiyo South'), ('Elgeyo-Marakwet', 'Marakwet East'), ('Elgeyo-Marakwet', 'Marakwet West'),
  ('Embu', 'Manyatta'), ('Embu', 'Mbeere North'), ('Embu', 'Mbeere South'), ('Embu', 'Runyenjes'),
  ('Garissa', 'Balambala'), ('Garissa', 'Dadaab'), ('Garissa', 'Fafi'), ('Garissa', 'Garissa Township'), ('Garissa', 'Ijara'), ('Garissa', 'Lagdera'),
  ('Homa Bay', 'Homa Bay Town'), ('Homa Bay', 'Kabondo Kasipul'), ('Homa Bay', 'Karachuonyo'), ('Homa Bay', 'Kasipul'), ('Homa Bay', 'Ndhiwa'), ('Homa Bay', 'Rangwe'), ('Homa Bay', 'Suba North'), ('Homa Bay', 'Suba South'),
  ('Isiolo', 'Isiolo North'), ('Isiolo', 'Isiolo South'),
  ('Kajiado', 'Kajiado Central'), ('Kajiado', 'Kajiado East'), ('Kajiado', 'Kajiado North'), ('Kajiado', 'Kajiado South'), ('Kajiado', 'Kajiado West'),
  ('Kakamega', 'Butere'), ('Kakamega', 'Ikolomani'), ('Kakamega', 'Khwisero'), ('Kakamega', 'Likuyani'), ('Kakamega', 'Lugari'), ('Kakamega', 'Lurambi'), ('Kakamega', 'Malava'), ('Kakamega', 'Matungu'), ('Kakamega', 'Mumias East'), ('Kakamega', 'Mumias West'), ('Kakamega', 'Navakholo'), ('Kakamega', 'Shinyalu'),
  ('Kericho', 'Ainamoi'), ('Kericho', 'Belgut'), ('Kericho', 'Bureti'), ('Kericho', 'Kipkelion East'), ('Kericho', 'Kipkelion West'), ('Kericho', 'Sigowet-Soin'),
  ('Kiambu', 'Gatundu North'), ('Kiambu', 'Gatundu South'), ('Kiambu', 'Githunguri'), ('Kiambu', 'Juja'), ('Kiambu', 'Kabete'), ('Kiambu', 'Kiambaa'), ('Kiambu', 'Kiambu'), ('Kiambu', 'Kikuyu'), ('Kiambu', 'Lari'), ('Kiambu', 'Limuru'), ('Kiambu', 'Ruiru'), ('Kiambu', 'Thika Town'),
  ('Kilifi', 'Ganze'), ('Kilifi', 'Kaloleni'), ('Kilifi', 'Kilifi North'), ('Kilifi', 'Kilifi South'), ('Kilifi', 'Magarini'), ('Kilifi', 'Malindi'), ('Kilifi', 'Rabai'),
  ('Kirinyaga', 'Gichugu'), ('Kirinyaga', 'Kirinyaga Central'), ('Kirinyaga', 'Mwea'), ('Kirinyaga', 'Ndia'),
  ('Kisii', 'Bobasi'), ('Kisii', 'Bonchari'), ('Kisii', 'Bomachoge Borabu'), ('Kisii', 'Bomachoge Chache'), ('Kisii', 'Kitutu Chache North'), ('Kisii', 'Kitutu Chache South'), ('Kisii', 'Nyaribari Chache'), ('Kisii', 'Nyaribari Masaba'), ('Kisii', 'South Mugirango'),
  ('Kisumu', 'Kisumu Central'), ('Kisumu', 'Kisumu East'), ('Kisumu', 'Kisumu West'), ('Kisumu', 'Muhoroni'), ('Kisumu', 'Nyakach'), ('Kisumu', 'Nyando'), ('Kisumu', 'Seme'),
  ('Kitui', 'Kitui Central'), ('Kitui', 'Kitui East'), ('Kitui', 'Kitui Rural'), ('Kitui', 'Kitui South'), ('Kitui', 'Kitui West'), ('Kitui', 'Mwingi Central'), ('Kitui', 'Mwingi North'), ('Kitui', 'Mwingi West'),
  ('Kwale', 'Kinango'), ('Kwale', 'Lunga Lunga'), ('Kwale', 'Matuga'), ('Kwale', 'Msambweni'),
  ('Laikipia', 'Laikipia East'), ('Laikipia', 'Laikipia North'), ('Laikipia', 'Laikipia West'),
  ('Lamu', 'Lamu East'), ('Lamu', 'Lamu West'),
  ('Machakos', 'Kangundo'), ('Machakos', 'Kathiani'), ('Machakos', 'Machakos Town'), ('Machakos', 'Masinga'), ('Machakos', 'Matungulu'), ('Machakos', 'Mavoko'), ('Machakos', 'Mwala'), ('Machakos', 'Yatta'),
  ('Makueni', 'Kaiti'), ('Makueni', 'Kibwezi East'), ('Makueni', 'Kibwezi West'), ('Makueni', 'Kilome'), ('Makueni', 'Makindu'), ('Makueni', 'Mbooni'),
  ('Mandera', 'Banissa'), ('Mandera', 'Lafey'), ('Mandera', 'Mandera East'), ('Mandera', 'Mandera North'), ('Mandera', 'Mandera South'), ('Mandera', 'Mandera West'),
  ('Marsabit', 'Laisamis'), ('Marsabit', 'Moyale'), ('Marsabit', 'North Horr'), ('Marsabit', 'Saku'),
  ('Meru', 'Buuri'), ('Meru', 'Central Imenti'), ('Meru', 'Igembe Central'), ('Meru', 'Igembe North'), ('Meru', 'Igembe South'), ('Meru', 'North Imenti'), ('Meru', 'South Imenti'), ('Meru', 'Tigania East'), ('Meru', 'Tigania West'),
  ('Migori', 'Awendo'), ('Migori', 'Kuria East'), ('Migori', 'Kuria West'), ('Migori', 'Nyatike'), ('Migori', 'Rongo'), ('Migori', 'Suna East'), ('Migori', 'Suna West'), ('Migori', 'Uriri'),
  ('Mombasa', 'Changamwe'), ('Mombasa', 'Jomvu'), ('Mombasa', 'Kisauni'), ('Mombasa', 'Likoni'), ('Mombasa', 'Mvita'), ('Mombasa', 'Nyali'),
  ('Murang''a', 'Gatanga'), ('Murang''a', 'Kandara'), ('Murang''a', 'Kangema'), ('Murang''a', 'Kiharu'), ('Murang''a', 'Kigumo'), ('Murang''a', 'Maragwa'), ('Murang''a', 'Mathioya'),
  ('Nairobi City', 'Dagoretti North'), ('Nairobi City', 'Dagoretti South'), ('Nairobi City', 'Embakasi Central'), ('Nairobi City', 'Embakasi East'), ('Nairobi City', 'Embakasi North'), ('Nairobi City', 'Embakasi South'), ('Nairobi City', 'Embakasi West'), ('Nairobi City', 'Kamukunji'), ('Nairobi City', 'Kasarani'), ('Nairobi City', 'Kibra'), ('Nairobi City', 'Langata'), ('Nairobi City', 'Makadara'), ('Nairobi City', 'Mathare'), ('Nairobi City', 'Roysambu'), ('Nairobi City', 'Ruaraka'), ('Nairobi City', 'Starehe'), ('Nairobi City', 'Westlands'),
  ('Nakuru', 'Bahati'), ('Nakuru', 'Gilgil'), ('Nakuru', 'Kuresoi North'), ('Nakuru', 'Kuresoi South'), ('Nakuru', 'Molo'), ('Nakuru', 'Naivasha'), ('Nakuru', 'Nakuru Town East'), ('Nakuru', 'Nakuru Town West'), ('Nakuru', 'Njoro'), ('Nakuru', 'Rongai'), ('Nakuru', 'Subukia'),
  ('Nandi', 'Aldai'), ('Nandi', 'Chesumei'), ('Nandi', 'Emgwen'), ('Nandi', 'Mosop'), ('Nandi', 'Nandi Hills'), ('Nandi', 'Tinderet'),
  ('Narok', 'Emurua Dikirr'), ('Narok', 'Kilgoris'), ('Narok', 'Narok East'), ('Narok', 'Narok North'), ('Narok', 'Narok South'), ('Narok', 'Narok West'),
  ('Nyamira', 'Borabu'), ('Nyamira', 'Kitutu Masaba'), ('Nyamira', 'North Mugirango'), ('Nyamira', 'West Mugirango'),
  ('Nyandarua', 'Kinangop'), ('Nyandarua', 'Kipipiri'), ('Nyandarua', 'Ndaragwa'), ('Nyandarua', 'Ol Jorok'), ('Nyandarua', 'Ol Kalou'),
  ('Nyeri', 'Kieni'), ('Nyeri', 'Mathira'), ('Nyeri', 'Mukurweini'), ('Nyeri', 'Nyeri Town'), ('Nyeri', 'Othaya'), ('Nyeri', 'Tetu'),
  ('Samburu', 'Samburu East'), ('Samburu', 'Samburu North'), ('Samburu', 'Samburu West'),
  ('Siaya', 'Alego Usonga'), ('Siaya', 'Bondo'), ('Siaya', 'Gem'), ('Siaya', 'Rarieda'), ('Siaya', 'Ugenya'), ('Siaya', 'Ugunja'),
  ('Taita-Taveta', 'Mwatate'), ('Taita-Taveta', 'Taveta'), ('Taita-Taveta', 'Voi'), ('Taita-Taveta', 'Wundanyi'),
  ('Tana River', 'Bura'), ('Tana River', 'Galole'), ('Tana River', 'Garsen'),
  ('Tharaka-Nithi', 'Chuka/Igambang''ombe'), ('Tharaka-Nithi', 'Maara'), ('Tharaka-Nithi', 'Tharaka'),
  ('Trans Nzoia', 'Cherangany'), ('Trans Nzoia', 'Endebess'), ('Trans Nzoia', 'Kiminini'), ('Trans Nzoia', 'Kwanza'), ('Trans Nzoia', 'Saboti'),
  ('Turkana', 'Loima'), ('Turkana', 'Turkana Central'), ('Turkana', 'Turkana East'), ('Turkana', 'Turkana North'), ('Turkana', 'Turkana South'), ('Turkana', 'Turkana West'),
  ('Uasin Gishu', 'Ainabkoi'), ('Uasin Gishu', 'Kapseret'), ('Uasin Gishu', 'Kesses'), ('Uasin Gishu', 'Moiben'), ('Uasin Gishu', 'Soy'), ('Uasin Gishu', 'Turbo'),
  ('Vihiga', 'Emuhaya'), ('Vihiga', 'Hamisi'), ('Vihiga', 'Luanda'), ('Vihiga', 'Sabatia'), ('Vihiga', 'Vihiga'),
  ('Wajir', 'Eldas'), ('Wajir', 'Tarbaj'), ('Wajir', 'Wajir East'), ('Wajir', 'Wajir North'), ('Wajir', 'Wajir South'), ('Wajir', 'Wajir West'),
  ('West Pokot', 'Kacheliba'), ('West Pokot', 'Kapenguria'), ('West Pokot', 'Pokot South'), ('West Pokot', 'Sigor')
on conflict (county, constituency) do nothing;

alter table public.locations enable row level security;
drop policy if exists "Locations are viewable by everyone" on public.locations;
create policy "Locations are viewable by everyone"
  on public.locations for select
  to anon, authenticated
  using (true);

create index if not exists locations_county_idx on public.locations (county);
create index if not exists posts_visibility_location_created_idx
  on public.posts (visibility, county, constituency, created_at desc);
create index if not exists profiles_location_idx
  on public.profiles (county, constituency);

drop policy if exists "Posts are viewable by everyone" on public.posts;
drop policy if exists "Posts are visible by audience" on public.posts;
create policy "Posts are visible by audience"
  on public.posts for select
  to anon, authenticated
  using (
    visibility = 'public'
    or user_id = auth.uid()
    or (
      auth.uid() is not null
      and visibility = 'county'
      and county = (select p.county from public.profiles p where p.id = auth.uid())
    )
    or (
      auth.uid() is not null
      and visibility = 'constituency'
      and county = (select p.county from public.profiles p where p.id = auth.uid())
      and constituency = (select p.constituency from public.profiles p where p.id = auth.uid())
    )
  );
